### ISSUE TITLE
Change Footer Details

### ISSUE THREAD

**Issue by mdsrk** [mdsrk/my-personal-website#1]
The Exisiting text is **© 2017 ProBootstrap:Frame. All Rights Reserved. 
Designed & Developed by ProBootstrap.com 
Demo Images by Unsplash**

Change it to
© 2017 All Rights Reserved.

**Comment by MDShahrouq** [comment]
hi, Please checkout the PR

**Comment by mdsrk** [comment]
@MDShahrouq Thanks for sending PR , i have Merged it
