### ISSUE TITLE
Change Contact Details

### ISSUE THREAD

**Issue by mdsrk** [mdsrk/my-personal-website#3]
Present : **EMAIL
probootstrap@gmail.com
PHONE
+30 976 1382 9921
FAX
+30 976 1382 9922
ADDRESS
San Francisco, CA 
4th Floor8 Lower 
San Francisco street, M1 50F**

Change it to : **
EMAIL
mdsrk@gmail.com
PHONE
+91-8147280120
ADDRESS
Azam Nagar,Bangalore**

**Comment by MDShahrouq** [comment]
Hi , I have sent PR just check it
