### ISSUE TITLE
Update the Following Elements

### ISSUE THREAD

**Issue by mdsrk** [mdsrk/my-personal-website#6]
Sitename : FRAME ==> SRK
Title : My Site ==> SRK

Remove two buttons i.e, Get Them now and See features
Replace the Following content (ProBootstrap.com Creates High Quality Bootstrap Template For Free) with (It's memorable. ...)

**Comment by mdsrk** [comment]
Please check it out

**Comment by MDShahrouq** [comment]
Please , check the PR

**Comment by mdsrk** [comment]
Fixed
